import type { UiLanguage } from "../../app/lib/ui-language";

const EN_LABELS: Record<string, string> = {
  "OB/GYNE Health Ed - Warning signs": "OB/GYNE Health Ed - Red flag sign to return to hospital",
};

const TH_LABELS: Record<string, string> = {
  "DOPS - Before: Indications/Complications": "DOPS - ก่อนทำ: ข้อบ่งชี้/ภาวะแทรกซ้อน",
  "DOPS - Before: Consent": "DOPS - ก่อนทำ: การขอความยินยอม",
  "DOPS - Before: Preparation": "DOPS - ก่อนทำ: การเตรียมความพร้อม",
  "DOPS - During: Patient Comfort": "DOPS - ระหว่างทำ: ความสบายของผู้ป่วย",
  "DOPS - During: Procedure Steps": "DOPS - ระหว่างทำ: ขั้นตอนหัตถการ",
  "DOPS - During: Aseptic": "DOPS - ระหว่างทำ: หลักปลอดเชื้อ",
  "DOPS - During: Problem Solving": "DOPS - ระหว่างทำ: การแก้ปัญหา",
  "DOPS - After: Post-procedure Care": "DOPS - หลังทำ: การดูแลหลังหัตถการ",
  "DOPS - After: Communication": "DOPS - หลังทำ: การสื่อสาร",
  "DOPS - Patient Empathy": "DOPS - ความเห็นอกเห็นใจผู้ป่วย",
  "DOPS - Pre Performance practice preparation": "DOPS - การเตรียมตัวก่อนปฏิบัติ",
  "DOPS - Overall Performance": "DOPS - ผลการประเมินโดยรวม",
  "Extern - History Taking": "Extern - การซักประวัติ",
  "Extern - Physical Exam": "Extern - การตรวจร่างกาย",
  "Extern - Diagnosis & Diff Dx": "Extern - การวินิจฉัยและวินิจฉัยแยกโรค",
  "Extern - Management Plan": "Extern - แผนการรักษา",
  "Extern - Communication Skills": "Extern - ทักษะการสื่อสาร",
  "Extern - Professionalism": "Extern - ความเป็นวิชาชีพ",
  "IM Health Ed - Assess baseline": "IM Health Ed - ประเมินความรู้พื้นฐานเดิม",
  "IM Health Ed - Information delivery": "IM Health Ed - การอธิบายข้อมูล",
  "IM Health Ed - Teach-back and engagement": "IM Health Ed - Teach-back และการมีส่วนร่วม",
  "IM Health Ed - Empowerment and shared planning": "IM Health Ed - การเสริมพลังและวางแผนร่วม",
  "IM Health Ed - Communication skills (patient)": "IM Health Ed - ทักษะการสื่อสารกับผู้ป่วย",
  "IM Health Ed - Professionalism checklist": "IM Health Ed - เช็กลิสต์ความเป็นวิชาชีพ",
  "Case Presentation - Content and currency": "Case Presentation - เนื้อหาและความทันสมัย",
  "Case Presentation - Evidence appraisal": "Case Presentation - การประเมินหลักฐาน",
  "Case Presentation - Clinical application": "Case Presentation - การประยุกต์ใช้ทางคลินิก",
  "Case Presentation - Teaching media": "Case Presentation - สื่อประกอบการสอน",
  "Case Presentation - Presentation skills": "Case Presentation - ทักษะการนำเสนอ",
  "Interesting Case - Patient summary": "Interesting Case - สรุปข้อมูลผู้ป่วย",
  "Interesting Case - Clinical diagnosis process": "Interesting Case - กระบวนการวินิจฉัย",
  "Interesting Case - Management and holistic care": "Interesting Case - การดูแลรักษาแบบองค์รวม",
  "Interesting Case - Discussion": "Interesting Case - การอภิปราย",
  "Interesting Case - Presentation media and delivery": "Interesting Case - สื่อและการถ่ายทอด",
  "Interesting Case General - Patient summary": "Interesting Case (General) - สรุปข้อมูลผู้ป่วย",
  "Interesting Case General - Clinical diagnosis process": "Interesting Case (General) - กระบวนการวินิจฉัย",
  "Interesting Case General - Management and holistic care": "Interesting Case (General) - การดูแลรักษาแบบองค์รวม",
  "Interesting Case General - Discussion": "Interesting Case (General) - การอภิปราย",
  "Interesting Case General - Presentation media and delivery": "Interesting Case (General) - สื่อและการถ่ายทอด",
  "OPD Assessment - History": "OPD Assessment - การซักประวัติ",
  "OPD Assessment - Physical examination": "OPD Assessment - การตรวจร่างกาย",
  "OPD Assessment - Problem list": "OPD Assessment - รายการปัญหา",
  "OPD Assessment - Provisional diagnosis": "OPD Assessment - การวินิจฉัยเบื้องต้น",
  "OPD Assessment - Differential diagnosis and discussion": "OPD Assessment - วินิจฉัยแยกโรคและอภิปราย",
  "OPD Assessment - Investigation and interpretation": "OPD Assessment - การส่งตรวจและแปลผล",
  "OPD Assessment - Management plan": "OPD Assessment - แผนการรักษา",
  "OPD Assessment - Overall result": "OPD Assessment - ผลรวมโดยรวม",
  "OPD Clinical - Foundation knowledge": "OPD Clinical - ความรู้พื้นฐาน",
  "OPD Clinical - Clinical evaluation": "OPD Clinical - การประเมินทางคลินิก",
  "OPD Clinical - Clinical reasoning and planning": "OPD Clinical - การคิดวิเคราะห์และวางแผน",
  "OPD Clinical - Management and follow-up": "OPD Clinical - การรักษาและติดตามผล",
  "OPD Clinical - Communication skills": "OPD Clinical - ทักษะการสื่อสาร",
  "OPD Clinical - Professionalism checklist": "OPD Clinical - เช็กลิสต์ความเป็นวิชาชีพ",
  "OPD Clinical - Overall Performance": "OPD Clinical - ผลการประเมินโดยรวม",
  "IPD Clinical - Clinical data and monitoring": "IPD Clinical - ข้อมูลทางคลินิกและการติดตาม",
  "IPD Clinical - Case presentation (SOAP)": "IPD Clinical - การนำเสนอเคส (SOAP)",
  "IPD Clinical - Clinical reasoning and management": "IPD Clinical - การคิดวิเคราะห์และการดูแลรักษา",
  "IPD Clinical - Procedural skill": "IPD Clinical - ทักษะหัตถการ",
  "IPD Clinical - Responsibility and punctuality": "IPD Clinical - ความรับผิดชอบและตรงต่อเวลา",
  "IPD Clinical - Clinical initiative and learning": "IPD Clinical - ความริเริ่มและการเรียนรู้",
  "IPD Clinical - Communication and interpersonal": "IPD Clinical - การสื่อสารและมนุษยสัมพันธ์",
  "IPD Clinical - Ethics and professional conduct": "IPD Clinical - จริยธรรมและความเป็นวิชาชีพ",
  "IPD Clinical - Overall Performance": "IPD Clinical - ผลการประเมินโดยรวม",
  "Anticipatory Guidance - History": "Anticipatory Guidance - การซักประวัติ",
  "Anticipatory Guidance - Physical examination": "Anticipatory Guidance - การตรวจร่างกาย",
  "Anticipatory Guidance - Problem list": "Anticipatory Guidance - รายการปัญหา",
  "Anticipatory Guidance - Management and anticipatory guidance":
    "Anticipatory Guidance - การดูแลรักษาและคำแนะนำเชิงป้องกัน",
  "Anticipatory Guidance - Overall result": "Anticipatory Guidance - ผลรวมโดยรวม",
  "OR Assessment - Surgical patient data": "OR Assessment - ข้อมูลผู้ป่วยศัลยกรรม",
  "OR Assessment - Disease background": "OR Assessment - พื้นฐานโรค",
  "OR Assessment - Surgical procedure knowledge": "OR Assessment - ความรู้หัตถการผ่าตัด",
  "OR Assessment - Sterile technique": "OR Assessment - เทคนิคปลอดเชื้อ",
  "OR Assessment - Operative field participation": "OR Assessment - การมีส่วนร่วมในสนามผ่าตัด",
  "OR Assessment - Professionalism checklist": "OR Assessment - เช็กลิสต์ความเป็นวิชาชีพ",
  "OR Assessment - Overall Performance": "OR Assessment - ผลการประเมินโดยรวม",
  "OB/GYNE Health Ed - Introduction": "OB/GYNE Health Ed - การเริ่มต้นและแนะนำตัว",
  "OB/GYNE Health Ed - Foundation": "OB/GYNE Health Ed - พื้นฐานความรู้และเหตุผลทางคลินิก",
  "OB/GYNE Health Ed - Technical instructions": "OB/GYNE Health Ed - ขั้นตอน/ทักษะเชิงเทคนิค",
  "OB/GYNE Health Ed - Lifestyle advice": "OB/GYNE Health Ed - คำแนะนำด้านการใช้ชีวิต",
  "OB/GYNE Health Ed - Warning signs":
    "OB/GYNE Health Ed - Red flag sign to return to hospital อาการที่ต้องมาโรงพยาบาล",
  "OB/GYNE Health Ed - Follow-up and questions": "OB/GYNE Health Ed - การนัดติดตามและตอบข้อสงสัย",
  "OB/GYNE Health Education - Overall result": "OB/GYNE Health Education - ผลรวมโดยรวม",
  "JC - 1.1 Rationale/Importance": "JC - 1.1 เหตุผล/ความสำคัญ",
  "JC - 1.2 Methodology Overview": "JC - 1.2 ภาพรวมวิธีวิจัย",
  "JC - 1.3 Results Overview": "JC - 1.3 ภาพรวมผลการศึกษา",
  "JC - 1.4 Discussion & Conclusion": "JC - 1.4 อภิปรายและสรุป",
  "JC - 2.1 Strengths & Limitations": "JC - 2.1 จุดแข็งและข้อจำกัด",
  "JC - 2.2 Clinical Application": "JC - 2.2 การประยุกต์ใช้ทางคลินิก",
  "JC - 2.3 Further Studies Needed": "JC - 2.3 ข้อเสนอการศึกษาต่อ",
  "JC - 2.4 Review & Summary": "JC - 2.4 ทบทวนและสรุป",
  "JC - 3.1 Preparation & Materials": "JC - 3.1 การเตรียมตัวและสื่อประกอบ",
  "JC - 3.2 Presentation Skills": "JC - 3.2 ทักษะการนำเสนอ",
  "JC - 3.3 Time Management": "JC - 3.3 การบริหารเวลา",
  "JC - 4.0 Ability to Answer Questions": "JC - 4.0 ความสามารถในการตอบคำถาม",
  "MSF - Continuous Prof. Development (C)": "MSF - การพัฒนาวิชาชีพต่อเนื่อง (C)",
  "MSF - Research & Innovation (R)": "MSF - วิจัยและนวัตกรรม (R)",
  "MSF - Resilience (R)": "MSF - ความยืดหยุ่น/ฟื้นตัว (R)",
  "MSF - Altruism (A)": "MSF - จิตอาสา/เห็นแก่ผู้อื่น (A)",
  "MSF - Mastery (M)": "MSF - ความเชี่ยวชาญ (M)",
  "MSF - Digital Literacy (D)": "MSF - ทักษะดิจิทัล (D)",
  "MSF - Professionalism (P)": "MSF - ความเป็นวิชาชีพ (P)",
  "MSF - Humility & Volunteerism (H)": "MSF - ความอ่อนน้อมและจิตอาสา (H)",
  "CbD - Data Gathering & Presentation": "CbD - การเก็บข้อมูลและการนำเสนอ",
  "CbD - Problem Summarization": "CbD - การสรุปปัญหา",
  "CbD - Diagnosis & Diff Dx": "CbD - การวินิจฉัยและวินิจฉัยแยกโรค",
  "CbD - Investigations": "CbD - การสืบค้นเพิ่มเติม",
  "CbD - Management & Prevention": "CbD - การรักษาและการป้องกัน",
  "CbD - Overall performance": "CbD - ผลการประเมินโดยรวม",
  "MiniCEX - History Taking": "MiniCEX - การซักประวัติ",
  "MiniCEX - Physical Exam": "MiniCEX - การตรวจร่างกาย",
  "MiniCEX - Diagnosis & Diff Dx": "MiniCEX - การวินิจฉัยและวินิจฉัยแยกโรค",
  "MiniCEX - Investigations": "MiniCEX - การสืบค้นเพิ่มเติม",
  "MiniCEX - Management Plan": "MiniCEX - แผนการรักษา",
  "MiniCEX - Patient Education/Counseling": "MiniCEX - สุขศึกษา/ให้คำปรึกษาผู้ป่วย",
  "MiniCEX - Communication Skills": "MiniCEX - ทักษะการสื่อสาร",
  "MiniCEX - Professionalism": "MiniCEX - ความเป็นวิชาชีพ",
  "MiniCEX - Over all performance": "MiniCEX - ผลการประเมินโดยรวม",
};

export function maskFormUiLabel(language: UiLanguage, englishLabel: string): string {
  if (language === "en") {
    return EN_LABELS[englishLabel] ?? englishLabel;
  }
  if (language === "th") {
    return TH_LABELS[englishLabel] ?? englishLabel;
  }
  return englishLabel;
}
